[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = { version = "0.4", features = ["serde"] }

rand = "0.8"

sha2 = "0.9"

serde = { version = "1.0", features = ["derive"] }

serde_json = "1.0"

cursive = "0.17"